# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'myServiceConnection'
    subscriptionId: '229024e2-8aa5-4a5f-8198-be8443b9808a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DevOps'
    location: 'East US'
    templateLocation: 'https://github.com/dsahoo165/Templates/blob/main/deploymentTemplate.json'
    csmFileLink: ''
    deploymentMode: 'Incremental'
